---
# Cài đặt kubeadm kubelet và kubectl cho control plane và worker node machine
- name: Install Common for master-node and worker node
  hosts: control_plane:worker_node
  gather_facts: true
  become: true
  tasks:
    # Config common setting
    - name: Setting common configuration for all nodes
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        br_netfilter
        EOF

        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF

        sudo sysctl --system
      # Cài kubeadl kubectl và kubelet
    - name: Install Kubeadm, Kubectl, Kubelet
      shell: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl

        mkdir -p /etc/apt/keyrings

        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg

        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

        sudo apt-get update

        sudo apt-mark unhold kubelet kubeadm kubectl

        sudo apt-get install -y kubelet=1.27.0-00 kubeadm=1.27.0-00 kubectl=1.27.0-00

        sudo apt-mark hold kubelet kubeadm kubectl
