---
- name: Copy monitoring directory to monitor EC2 instance
  hosts: monitor
  gather_facts: true
  become: true
  tasks:
    # Copy thư mục monitoring chứa file docker compose để chạy lên monitoring server và các file cần thiết khác
    - name: Copy monitoring directory to EC2
      synchronize:
        src: ./monitoring
        dest: /home/ubuntu/monitornig
        mode: push
      delegate_to: localhost
    # Chạy lên monitoring server
    - name: Install Container Engine
      shell: |
        docker-compose -f /home/ubuntu/monitoring/docker-compose.yml up -d
