---
- name: Copy monitoring directory to monitor EC2 instance
  hosts: monitor
  gather_facts: true
  become: true
  tasks:
    - name: Copy monitoring directory to EC2
      synchronize:
        src: ./monitoring
        dest: /home/ubuntu/monitornig
        mode: push
      delegate_to: localhost
    # Cài đặt docker engine, cấu hình và cấp quyền chạy docker
    - name: Install Container Engine
      shell: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg lsb-release
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        sudo apt-get install docker.io docker-compose -y
        systemctl enable docker.service
        systemctl start docker.service

        cat <<EOF | sudo tee /etc/docker/daemon.json
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
        EOF
        sudo systemctl enable docker
        sudo systemctl daemon-reload
        sudo systemctl restart docker
        sudo chmod 777 /var/run/docker.sock
          # Cài đặt docker engine, cấu hình và cấp quyền chạy docker
    # Chạy lên monitoring server
    - name: Install Container Engine
      shell: |
        docker-compose -f /home/ubuntu/monitoring/docker-compose.yml up -d
